#!/bin/sh
sudo add-apt-repository -y ppa:ondrej/php
sudo apt install -y php8.0-cli \
                    php8.0-amqp \
                    php8.0-bcmath \
                    php8.0-bz2 \
                    php8.0-curl \
                    php8.0-gd \
                    php8.0-imap \
                    php8.0-intl \
                    php8.0-ldap \
                    php8.0-mbstring \
                    php8.0-mysql \
                    php8.0-pgsql \
                    php8.0-soap \
                    php8.0-xml \
                    php8.0-xsl \
                    php8.0-zip \
                    php7.4-cli \
                    php7.4-amqp \
                    php7.4-bcmath \
                    php7.4-bz2 \
                    php7.4-curl \
                    php7.4-gd \
                    php7.4-imap \
                    php7.4-intl \
                    php7.4-ldap \
                    php7.4-mbstring \
                    php7.4-mysql \
                    php7.4-pgsql \
                    php7.4-soap \
                    php7.4-xml \
                    php7.4-xsl \
                    php7.4-zip \
                    php7.3-cli \
                    php7.3-amqp \
                    php7.3-bcmath \
                    php7.3-bz2 \
                    php7.3-curl \
                    php7.3-gd \
                    php7.3-imap \
                    php7.3-intl \
                    php7.3-ldap \
                    php7.3-mbstring \
                    php7.3-mysql \
                    php7.3-pgsql \
                    php7.3-soap \
                    php7.3-xml \
                    php7.3-xsl \
                    php7.3-zip \
                    php7.2-cli \
                    php7.2-amqp \
                    php7.2-bcmath \
                    php7.2-bz2 \
                    php7.2-curl \
                    php7.2-gd \
                    php7.2-imap \
                    php7.2-intl \
                    php7.2-ldap \
                    php7.2-mbstring \
                    php7.2-mysql \
                    php7.2-pgsql \
                    php7.2-soap \
                    php7.2-xml \
                    php7.2-xsl \
                    php7.2-zip
echo "Installed php"
